[package]
name = "ruft"
version = "0.1.0"
authors = ["Shamil Gadelshin <shamilgadelshin@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
crossbeam-channel = "0.3"
chrono = "0.4"
log = "0.4"
env_logger = "0.6"